from collections import Counter
seqs = {
 "β-lactoglobulin": ("P02754", "LIVTQTMKGLDIQKVAGTWYSLAMAASDISLLDAQSAPLRVYVEELKPTPEGDLEILLQKWENGECAQKKIIAEKTKIPAVFKIDALNENKVLVLDTDYKKYLLFCMENSAEPEQSLACQCLVRTPEVDDEALEKFDKALKALPMHIRLSFNPTQLEEQCHI"),
 "α-lactalbumin": ("P00711", "EQLTKCEVFRELKDLKGYGGVSLPEWVCTTFHTSGYDTQAIVQNNDSTEYGLFQINNKIWCKDDQNPHSSNICNISCDKFLDDDLTDDIMCVKKILDKVGINYWLAHKALCSEKLDQWLCEKL"),
 "αs1-casein": ("P02662", "RPKHPIKHQGLPQEVLNENLLRFFVAPFPEVFGKEKVNELSKDIGSESTEDQAMEDIKQMEAESISSSEEIVPNSVEQKHIQKEDVPSERYLGYLEQLLRLKKYKVPQLEIVPNSAEERLHSMKEGIHAQQKEPMIGVNQELAYFYPELFRQFYQLDAYPSGAWYYVPLGTQYTDAPSFSDIPNPIGSENSEKTTMPLW"),
 "β-casein": ("P02666", "RELEELNVPGEIVESLSSSEESITRINKKIEKFQSEEQQQTEDELQDKIHPFAQTQSLVYPFPGPIPNSLPQNIPPLTQTPVVVPPFLQPEVMGVSKVKEAMAPKHKEMPFPKYPVEPFTESQSLTLTDVENLHLPLPLLQSWMHQPHQPLPPTVMFPPQSVLSLSQSKVLPVPQKAVPYPQRDMPIQAFLLYQEPVLGPVRGPFPIIV"),
 "κ-casein": ("P02668", "QEQNQEQPIRCEKDERFFSDKIAKYIPIQYVLSRYPSYGLNYYQQKPVALINNQFLPYPYYAKPAAVRSPAQILQWQVLSNTVPAKSCQAQPTTMARHPHPHLSFMAIPPKKNQDKTEIPTINTIASGEPTSTPTTEAVESTVATLEDSPEVIESPPEINTVQVTSTAV"),
 "α-zein": ("P02859", "MAAKIFCLLMLLGLSASAATATIFPQCSQAPIASLLPPYLSPAVSSVCENPILQPYRIQQAIAAGILPLSPLFLQQSSALLQQLPLVHLLAQNIRAQQLQQLVLANLAAYSQQQQFLPFNQLAALNSASYLQQQQLPFSQLPAAYPQQFLPFNQLAALNSPAYLQQQQLLPFSQLAGVSPATFLTQPQLLPFYQHAAPNAGTLLQLQQLLPFNQLALTNLAAFYQQPIIGGALF"[21:]),
}
HYD=set('AVLIMFWPG'); POL=set('STNQCY'); CHG=set('DEKRH')
rows=[]
for k,(acc,s) in seqs.items():
    n=len(s)
    h=sum(a in HYD for a in s)/n*100; p=sum(a in POL for a in s)/n*100; c=sum(a in CHG for a in s)/n*100
    top=', '.join(f"{a} {round(v/n*100)}%" for a,v in Counter(s).most_common(3))
    rows.append((k,acc,n,h,p,c,top))
    print(f"{k:17s} {acc}  n={n:3d}  hydrophobic {h:4.1f}%  polar {p:4.1f}%  charged {c:4.1f}%   top: {top}")
import json; json.dump([{'name':r[0],'acc':r[1],'n':r[2],'hyd':r[3],'pol':r[4],'chg':r[5],'top':r[6]} for r in rows], open('/tmp/comp.json','w'))
